alter table Blog drop foreign key FK1FA3C24F2DD20D;
alter table Foo drop foreign key FK114A61A27D6B;
alter table FooInfo drop foreign key FK3A9D2A741A29ED1;
alter table MetricValue drop foreign key FKFB5361811D79FA59;
alter table PromotionRuleParams drop foreign key FK8854C0852C537632;
alter table TCustomerGroup drop foreign key FKCB4D194D508DE1D;
alter table TCustomerGroup drop foreign key FKCB4D194D45469C26;
alter table TDispatchingGift drop foreign key FK2281D784E93B81C5;
alter table TDispatchingGift drop foreign key FK2281D784DBBD74A1;
alter table TEvalMetrics drop foreign key FKDEE6EB93DCB4061D;
alter table TEvalMetrics drop foreign key FKDEE6EB93D1DE5F21;
alter table TPromotionPlan drop foreign key FK77034A78508DE1D;
alter table TPromotionPlan drop foreign key FK77034A784C1A050D;
alter table TPromotionPlan drop foreign key FK77034A785E55FE06;
alter table TRolePermissions drop foreign key FKAA8DB3AB1E777EC;
alter table TUserInfo drop foreign key FK9A67B78DB73CCD56;
alter table TUserRoles drop foreign key FKB30E97BEB1E777EC;
alter table TUserRoles drop foreign key FKB30E97BEB73CCD56;
alter table authors drop foreign key FKD977104835B728BB;
alter table authors drop foreign key FKD9771048A302392F;
alter table knc_prsn drop foreign key FKD46A595C67328017;
drop table if exists Author;
drop table if exists Bar;
drop table if exists Blog;
drop table if exists Book;
drop table if exists Foo;
drop table if exists FooInfo;
drop table if exists MetricValue;
drop table if exists PromotionRuleParams;
drop table if exists TASource;
drop table if exists TBSource;
drop table if exists TCSource;
drop table if exists TCustomerGroup;
drop table if exists TDispatchingGift;
drop table if exists TEvalMetrics;
drop table if exists TEvaluation;
drop table if exists TGift;
drop table if exists TLog;
drop table if exists TMetric;
drop table if exists TPointType;
drop table if exists TPromotionPlan;
drop table if exists TRole;
drop table if exists TRolePermissions;
drop table if exists TRules;
drop table if exists TUser;
drop table if exists TUserInfo;
drop table if exists TUserRoles;
drop table if exists authors;
drop table if exists knc_cust;
drop table if exists knc_prsn;
create table Author (id bigint not null auto_increment, name varchar(255), primary key (id)) type=InnoDB;
create table Bar (id bigint not null, name varchar(255), primary key (id)) type=InnoDB;
create table Blog (id bigint not null auto_increment, name varchar(255), author bigint, primary key (id)) type=InnoDB;
create table Book (id bigint not null auto_increment, name varchar(255), primary key (id)) type=InnoDB;
create table Foo (id bigint not null, amount numeric(19,2), date datetime, name varchar(255), bar bigint, F varchar(255), I char(1), L varchar(255), primary key (id)) type=InnoDB;
create table FooInfo (foo bigint not null, val varchar(255), name varchar(80) not null, primary key (foo, name)) type=InnoDB;
create table MetricValue (F_Id bigint not null auto_increment, F_DimensionType varchar(255), F_Dimension varchar(255), F_MetricId bigint, F_TargetType varchar(255), F_TargetId bigint, F_QuotaValue numeric(19,2), F_Frequence varchar(255), F_Date datetime, primary key (F_Id)) type=InnoDB;
create table PromotionRuleParams (PID bigint not null, val varchar(255), name varchar(80) not null, primary key (PID, name)) type=InnoDB;
create table TASource (id bigint not null auto_increment, name varchar(255), atype varchar(255), primary key (id)) type=InnoDB;
create table TBSource (id bigint not null auto_increment, name varchar(255), btype varchar(255), primary key (id)) type=InnoDB;
create table TCSource (id bigint not null auto_increment, name varchar(255), ctype varchar(255), primary key (id)) type=InnoDB;
create table TCustomerGroup (idno bigint not null auto_increment, creationDate datetime, name varchar(255), description varchar(255), frule varchar(255), creator varchar(255), evaluation bigint, parent bigint, primary key (idno)) type=InnoDB;
create table TDispatchingGift (idno bigint not null auto_increment, applyDate datetime, customer varchar(255), gift bigint, quantity integer, status integer, primary key (idno)) type=InnoDB;
create table TEvalMetrics (eid bigint not null, mid bigint not null) type=InnoDB;
create table TEvaluation (idno bigint not null auto_increment, creationDate datetime, creator varchar(255), description varchar(255), formula varchar(255), name varchar(255), type varchar(255), primary key (idno)) type=InnoDB;
create table TGift (idno bigint not null auto_increment, availableQuantity integer, costPrice numeric(19,2), description varchar(255), exchangeRule varchar(255), marketPrice numeric(19,2), name varchar(255), seqno varchar(255) unique, image longblob, imageFileName varchar(255), primary key (idno)) type=InnoDB;
create table TLog (id bigint not null auto_increment, log varchar(255), tablename varchar(255), sourceid bigint, primary key (id)) type=InnoDB;
create table TMetric (idno bigint not null auto_increment, description varchar(255), formula varchar(255), type varchar(255), frequence varchar(255), name varchar(255), ratio varchar(255), unit varchar(255), primary key (idno)) type=InnoDB;
create table TPointType (idno bigint not null auto_increment, description varchar(255), name varchar(255), primary key (idno)) type=InnoDB;
create table TPromotionPlan (idno bigint not null auto_increment, creationDate datetime, creator varchar(255), description varchar(255), endDate datetime, evaluation bigint, name varchar(255), frule bigint, startDate datetime, status varchar(255), target bigint not null, primary key (idno)) type=InnoDB;
create table TRole (idno bigint not null auto_increment, name varchar(255), description varchar(255), primary key (idno)) type=InnoDB;
create table TRolePermissions (RoleId bigint not null, Permission varchar(255)) type=InnoDB;
create table TRules (idno bigint not null auto_increment, description varchar(255), name varchar(255), frule text, type varchar(255), mapping text, primary key (idno)) type=InnoDB;
create table TUser (idno bigint not null auto_increment, creationDate datetime, disabled bit, disabledDate datetime, ip varchar(255), lastAccessDate datetime, name varchar(255), password varchar(255), superuser bit, primary key (idno)) type=InnoDB;
create table TUserInfo (userId bigint not null, val varchar(255), name varchar(80) not null, primary key (userId, name)) type=InnoDB;
create table TUserRoles (userId bigint not null, roleId bigint not null, primary key (userId, roleId)) type=InnoDB;
create table authors (id bigint not null, elt bigint not null) type=InnoDB;
create table knc_cust (custno varchar(255) not null, custna varchar(255), primary key (custno)) type=InnoDB;
create table knc_prsn (custno varchar(255) not null, mobitl varchar(255), primary key (custno)) type=InnoDB;
alter table Blog add index FK1FA3C24F2DD20D (author), add constraint FK1FA3C24F2DD20D foreign key (author) references Author (id);
alter table Foo add index FK114A61A27D6B (bar), add constraint FK114A61A27D6B foreign key (bar) references Bar (id);
alter table FooInfo add index FK3A9D2A741A29ED1 (foo), add constraint FK3A9D2A741A29ED1 foreign key (foo) references Foo (id);
alter table MetricValue add index FKFB5361811D79FA59 (F_MetricId), add constraint FKFB5361811D79FA59 foreign key (F_MetricId) references TMetric (idno);
alter table PromotionRuleParams add index FK8854C0852C537632 (PID), add constraint FK8854C0852C537632 foreign key (PID) references TPromotionPlan (idno);
alter table TCustomerGroup add index FKCB4D194D508DE1D (evaluation), add constraint FKCB4D194D508DE1D foreign key (evaluation) references TEvaluation (idno);
alter table TCustomerGroup add index FKCB4D194D45469C26 (parent), add constraint FKCB4D194D45469C26 foreign key (parent) references TCustomerGroup (idno);
alter table TDispatchingGift add index FK2281D784E93B81C5 (gift), add constraint FK2281D784E93B81C5 foreign key (gift) references TGift (idno);
alter table TDispatchingGift add index FK2281D784DBBD74A1 (customer), add constraint FK2281D784DBBD74A1 foreign key (customer) references knc_cust (custno);
alter table TEvalMetrics add index FKDEE6EB93DCB4061D (mid), add constraint FKDEE6EB93DCB4061D foreign key (mid) references TMetric (idno);
alter table TEvalMetrics add index FKDEE6EB93D1DE5F21 (eid), add constraint FKDEE6EB93D1DE5F21 foreign key (eid) references TEvaluation (idno);
alter table TPromotionPlan add index FK77034A78508DE1D (evaluation), add constraint FK77034A78508DE1D foreign key (evaluation) references TEvaluation (idno);
alter table TPromotionPlan add index FK77034A784C1A050D (target), add constraint FK77034A784C1A050D foreign key (target) references TCustomerGroup (idno);
alter table TPromotionPlan add index FK77034A785E55FE06 (frule), add constraint FK77034A785E55FE06 foreign key (frule) references TRules (idno);
alter table TRolePermissions add index FKAA8DB3AB1E777EC (RoleId), add constraint FKAA8DB3AB1E777EC foreign key (RoleId) references TRole (idno);
alter table TUserInfo add index FK9A67B78DB73CCD56 (userId), add constraint FK9A67B78DB73CCD56 foreign key (userId) references TUser (idno);
alter table TUserRoles add index FKB30E97BEB1E777EC (roleId), add constraint FKB30E97BEB1E777EC foreign key (roleId) references TRole (idno);
alter table TUserRoles add index FKB30E97BEB73CCD56 (userId), add constraint FKB30E97BEB73CCD56 foreign key (userId) references TUser (idno);
alter table authors add index FKD977104835B728BB (id), add constraint FKD977104835B728BB foreign key (id) references Book (id);
alter table authors add index FKD9771048A302392F (elt), add constraint FKD9771048A302392F foreign key (elt) references Author (id);
alter table knc_prsn add index FKD46A595C67328017 (custno), add constraint FKD46A595C67328017 foreign key (custno) references knc_cust (custno);
