/* Generated By:JJTree: Do not edit this line. /Users/jeffrey/Documents/jxb/ninecube/saturn/src/net/ninecube/saturn/ast/RuleParserVisitor.java */

package net.ninecube.saturn.ast;

public interface RuleParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Start node, Object data);
  public Object visit(Filter node, Object data);
  public Object visit(RegularRuleRegion node, Object data);
  public Object visit(CycleRuleRegion node, Object data);
  public Object visit(RegionProperty node, Object data);
  public Object visit(OrExpression node, Object data);
  public Object visit(AndExpression node, Object data);
  public Object visit(RelationalExpression node, Object data);
  public Object visit(AddExpression node, Object data);
  public Object visit(MultiExpression node, Object data);
  public Object visit(UnaryExpression node, Object data);
  public Object visit(VariableLiteral node, Object data);
  public Object visit(Function node, Object data);
  public Object visit(ArgumentList node, Object data);
  public Object visit(NamedArgumentList node, Object data);
  public Object visit(NamedArgument node, Object data);
  public Object visit(FunctionMapCall node, Object data);
  public Object visit(NumberLiteral node, Object data);
  public Object visit(StringLiteral node, Object data);
  public Object visit(BooleanLiteral node, Object data);
  public Object visit(Name node, Object data);
  public Object visit(AggStatement node, Object data);
  public Object visit(OrderStatement node, Object data);
  public Object visit(FunctionStatement node, Object data);
  public Object visit(BlockStatement node, Object data);
  public Object visit(AssignmentStatement node, Object data);
  public Object visit(SwitchStatement node, Object data);
  public Object visit(SwitchCase node, Object data);
  public Object visit(IfStatement node, Object data);
  public Object visit(skitToNextStatement node, Object data);
}
