/* Generated By:JJTree: Do not edit this line. /Users/jeffrey/Documents/jxb/ninecube/saturn/src/net/ninecube/saturn/ast/RuleParserTreeConstants.java */

package net.ninecube.saturn.ast;

public interface RuleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFILTER = 1;
  public int JJTREGULARRULEREGION = 2;
  public int JJTCYCLERULEREGION = 3;
  public int JJTREGIONPROPERTY = 4;
  public int JJTVOID = 5;
  public int JJTOREXPRESSION = 6;
  public int JJTANDEXPRESSION = 7;
  public int JJTRELATIONALEXPRESSION = 8;
  public int JJTADDEXPRESSION = 9;
  public int JJTMULTIEXPRESSION = 10;
  public int JJTUNARYEXPRESSION = 11;
  public int JJTVARIABLELITERAL = 12;
  public int JJTFUNCTION = 13;
  public int JJTARGUMENTLIST = 14;
  public int JJTNAMEDARGUMENTLIST = 15;
  public int JJTNAMEDARGUMENT = 16;
  public int JJTFUNCTIONMAPCALL = 17;
  public int JJTNUMBERLITERAL = 18;
  public int JJTSTRINGLITERAL = 19;
  public int JJTBOOLEANLITERAL = 20;
  public int JJTNAME = 21;
  public int JJTAGGSTATEMENT = 22;
  public int JJTORDERSTATEMENT = 23;
  public int JJTFUNCTIONSTATEMENT = 24;
  public int JJTBLOCKSTATEMENT = 25;
  public int JJTASSIGNMENTSTATEMENT = 26;
  public int JJTSWITCHSTATEMENT = 27;
  public int JJTSWITCHCASE = 28;
  public int JJTIFSTATEMENT = 29;
  public int JJTSKITTONEXTSTATEMENT = 30;


  public String[] jjtNodeName = {
    "Start",
    "Filter",
    "RegularRuleRegion",
    "CycleRuleRegion",
    "RegionProperty",
    "void",
    "OrExpression",
    "AndExpression",
    "RelationalExpression",
    "AddExpression",
    "MultiExpression",
    "UnaryExpression",
    "VariableLiteral",
    "Function",
    "ArgumentList",
    "NamedArgumentList",
    "NamedArgument",
    "FunctionMapCall",
    "NumberLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "Name",
    "AggStatement",
    "OrderStatement",
    "FunctionStatement",
    "BlockStatement",
    "AssignmentStatement",
    "SwitchStatement",
    "SwitchCase",
    "IfStatement",
    "skitToNextStatement",
  };
}
