/* Generated By:JJTree: Do not edit this line. skitToNextStatement.java */

package net.ninecube.saturn.ast;

public class skitToNextStatement extends SimpleNode {
  public skitToNextStatement(int id) {
    super(id);
  }

  public skitToNextStatement(RuleParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RuleParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
