/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package net.ninecube.fishman.parser;

public interface ParserConstants {

  int EOF = 0;
  int STATICBLOCK = 2;
  int BEGINTAGBLOCK = 8;
  int ENDTAGBLOCK = 9;
  int EQ = 11;
  int QUOTE = 12;
  int NAME = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int TAGEND = 16;

  int DEFAULT = 0;
  int COMMENT = 1;
  int IN_TAGBLOCK = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"<!--\"",
    "<STATICBLOCK>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "<BEGINTAGBLOCK>",
    "<ENDTAGBLOCK>",
    "<token of kind 10>",
    "\"=\"",
    "<QUOTE>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\"-->\"",
  };

}
