
create table REPORT_CHART (
CHART_ID integer not null auto_increment, 
NAME varchar(255) not null unique, 
DESCRIPTION varchar(255) not null, 
CHART_QUERY text not null, 
CHART_TYPE integer not null, 
WIDTH integer not null, 
HEIGHT integer not null, 
X_AXIS_LABEL varchar(255), 
Y_AXIS_LABEL varchar(255), 
DATASOURCE_ID integer, 
SHOW_LEGEND bit not null, 
SHOW_TITLE bit not null, 
PLOT_ORIENTATION integer, 
REPORT_ID integer, 
SHOW_VALUES bit not null, 
primary key (CHART_ID), unique (NAME));
create table REPORT (
REPORT_ID integer not null auto_increment, 
NAME varchar(255) not null unique, 
DESCRIPTION varchar(255) not null, 
REPORT_FILE varchar(255) not null, 
PDF_EXPORT bit not null, 
CSV_EXPORT bit not null, 
XLS_EXPORT bit not null, 
HTML_EXPORT bit not null, 
CHART_ID integer, 
REPORT_QUERY text, 
DATASOURCE_ID integer, 
FILL_VIRTUAL bit not null, 
EXCEL_EXPORT bit not null, 
TEXT_EXPORT bit not null, 
RTF_EXPORT bit not null, 
EXPORT_OPTION_ID integer, 
HIDDEN_REPORT bit not null, 
primary key (REPORT_ID), unique (NAME));


INSERT INTO REPORT_DATASOURCE VALUES(2,'OpenReports Sample Data','org.hsqldb.jdbcDriver','jdbc:hsqldb:hsql://127.0.0.1:9001/sample','sa','',2,20,1800,NULL,FALSE);
INSERT INTO REPORT_DATASOURCE VALUES(3,'OpenReports','org.hsqldb.jdbcDriver','jdbc:hsqldb:hsql://127.0.0.1:9001/openreports','sa','',2,20,1800,NULL,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(9,'MaxOrderDate','Date','java.util.Date','',NULL,'Max Order Date ',TRUE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(11,'Footer','Text','java.lang.String','',NULL,'Footer Text ',FALSE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(19,'YesNo','Boolean','java.lang.Boolean','',NULL,'Show Footer',FALSE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(20,'ProductCode','Query','java.lang.String','select productcode, productname from products order by productname',2,'Product Code ',TRUE,TRUE);
INSERT INTO REPORT_PARAMETER VALUES(21,'CustomerNumber','Query','java.lang.String','select customernumber, customername from customers order by customername',2,'Customer Number ',TRUE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(22,'ProductLine','Query','java.lang.String','select distinct productline from products order by productline',2,'Product Line',TRUE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(23,'ProductCodes','Query','java.lang.String','select distinct productcode, productname from products \r\nwhere productline = $P{ProductLine}\r\norder by productname',2,'Product Codes ',FALSE,TRUE);
INSERT INTO REPORT_PARAMETER VALUES(24,'Country','Query','java.lang.String','select distinct country from customers \r\norder by country',2,'Country',TRUE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(25,'City','Text','java.lang.String','',NULL,'City',FALSE,FALSE);
INSERT INTO REPORT_PARAMETER VALUES(26,'MinCreditLimit','List','java.lang.Integer','50000|100000|125000|150000',NULL,'Minimum Credt Limit',TRUE,FALSE);

INSERT INTO REPORT VALUES(13,'Orders By Year and Month','ChartReport - XY chart','-1',TRUE,FALSE,FALSE,TRUE,4,'',NULL,FALSE,FALSE,FALSE,FALSE,17,FALSE);
INSERT INTO REPORT VALUES(14,'Orders By Date','ChartReport - Time Chart','-1',TRUE,FALSE,FALSE,TRUE,5,'',NULL,FALSE,FALSE,FALSE,FALSE,16,FALSE);
INSERT INTO REPORT VALUES(33,'Regional Budget Variances','QueryReport - JFreeReport template example','RegionalBudgetVariances.xml',TRUE,FALSE,TRUE,TRUE,NULL,'select region, department, positiontitle, actual, budget, variance\r\nfrom quadrant_actuals\r\norder by region, department, positiontitle',2,FALSE,FALSE,FALSE,TRUE,19,FALSE);
INSERT INTO REPORT VALUES(37,'Employee List By Job Title','QueryReport - Basic Example ','-1',FALSE,FALSE,FALSE,FALSE,NULL,'select jobtitle as "Job Title", lastname as "Last Name", firstname as "First Name", extension,email  from employees\r\norder by jobtitle, lastname',2,FALSE,FALSE,FALSE,FALSE,23,FALSE);
INSERT INTO REPORT VALUES(38,'Orders List By Product and Date','QueryReport - Parameter Example','-1',FALSE,FALSE,FALSE,FALSE,NULL,'select orderdate as "Order Date", productname as "Product", quantityordered as "Quantity", priceeach as "Price", quantityordered * priceeach as "Total", status, comments\r\n from orders, orderdetails, products where orders.ordernumber = orderdetails.ordernumber\r\nand orderdetails.productcode = products.productcode and orderdate <= $P{MaxOrderDate}\r\nand productcode in ($P!{ProductCode})',2,FALSE,FALSE,FALSE,FALSE,24,FALSE);
INSERT INTO REPORT VALUES(39,'Customer List','QueryReport - Template with multiple DrillDown reports','CustomerListWithTemplate.vm',FALSE,FALSE,FALSE,FALSE,NULL,'select customernumber, customername as "Name", addressline1 as "Address", city, state, postalcode, country from customers\r\norder by customername',2,FALSE,FALSE,FALSE,FALSE,25,FALSE);
INSERT INTO REPORT VALUES(40,'Orders By Customer','QueryReport - DrillDown - Hidden','-1',FALSE,FALSE,FALSE,FALSE,NULL,'select orderdate as "Order Date", productname as "Product", quantityordered as "Quantity", priceeach as "Price", quantityordered * priceeach as "Total", status, comments\r\n from orders, orderdetails, products where orders.ordernumber = orderdetails.ordernumber\r\nand orderdetails.productcode = products.productcode and customernumber = $P{CustomerNumber}\r\n',2,FALSE,FALSE,FALSE,FALSE,26,TRUE);
INSERT INTO REPORT VALUES(41,'Orders By Product Line','ChartReport - Pie Chart Example with Parameter','-1',TRUE,FALSE,FALSE,FALSE,9,'',NULL,FALSE,FALSE,FALSE,FALSE,27,FALSE);
INSERT INTO REPORT VALUES(42,'Products By Line','ChartReport - Bar Chart with DrillDown (Pro only) and Show Values turned on','-1',TRUE,FALSE,FALSE,FALSE,10,'',NULL,FALSE,FALSE,FALSE,FALSE,28,FALSE);
INSERT INTO REPORT VALUES(46,'Product Line','QueryReport -- DrillDown - Hidden','-1',FALSE,FALSE,FALSE,FALSE,NULL,'select productline as "Line", productname as "Name", productvendor as "Vendor", productdescription as "Description", quantityinstock as "Quantity", buyprice as "Price", msrp as "MSRP" from products where productline = $P{DrillDown}',2,FALSE,FALSE,FALSE,FALSE,32,TRUE);
INSERT INTO REPORT VALUES(47,'Product Line Inventory','ChartReport - Ring Chart','-1',TRUE,FALSE,FALSE,FALSE,11,'',NULL,FALSE,FALSE,FALSE,FALSE,33,FALSE);
INSERT INTO REPORT VALUES(48,'Customer List with Credit Limit','JasperReport - Basic Example','CustomerList.jasper',TRUE,FALSE,TRUE,TRUE,NULL,'',2,FALSE,TRUE,FALSE,TRUE,34,FALSE);
INSERT INTO REPORT VALUES(49,'Product Orders','JasperReport - Advanced Parameter Example','ProductOrders.jasper',TRUE,TRUE,TRUE,TRUE,NULL,'',2,FALSE,TRUE,FALSE,TRUE,35,FALSE);
INSERT INTO REPORT VALUES(50,'Customer Credit Limits By Country','JasperReport - SubReport Example With Images','AddressMasterReport.jasper',TRUE,FALSE,FALSE,TRUE,NULL,'',2,FALSE,FALSE,FALSE,TRUE,36,FALSE);
INSERT INTO REPORT VALUES(53,'Customer Spreadsheet','SpreadsheetReport - Basic Example','Customers.xls',FALSE,FALSE,TRUE,FALSE,NULL,'select * from customers order by customername',2,FALSE,FALSE,FALSE,FALSE,39,FALSE);
INSERT INTO REPORT VALUES(54,'Product Line Summary','SpreadsheetReport - Advanced Example with Charts','ProductLines.xls',FALSE,FALSE,FALSE,FALSE,NULL,'select productline, sum(quantityinstock)\r\nfrom products\r\ngroup by productline\r\norder by productline',2,FALSE,FALSE,FALSE,FALSE,40,FALSE);
INSERT INTO REPORT VALUES(55,'OpenReports Activity','SpreadsheetReport - Embedded SQL example','OpenReportsActivity.xls',TRUE,FALSE,FALSE,FALSE,NULL,'',3,FALSE,FALSE,FALSE,FALSE,41,FALSE);
INSERT INTO REPORT VALUES(56,'Brochure','JasperReport - Basic Image example','BrochureReport.jasper',TRUE,TRUE,TRUE,TRUE,NULL,'',NULL,FALSE,TRUE,TRUE,TRUE,42,FALSE);
INSERT INTO REPORT VALUES(57,'Customer List  with Drill Down','JasperReport - Drill Down example','CustomerListWithDrillDown.jasper',TRUE,FALSE,FALSE,TRUE,NULL,'',2,FALSE,FALSE,FALSE,FALSE,43,FALSE);
INSERT INTO REPORT VALUES(58,'Multiple DataSource Report','BIRT Report - Multiple DataSources Example','MultipleDataSourcesReport.rptdesign',TRUE,FALSE,FALSE,TRUE,NULL,'',NULL,FALSE,FALSE,FALSE,FALSE,44,FALSE);
INSERT INTO REPORT VALUES(59,'Customer List (BIRT)','BIRT Report - Basic Example','CustomerList.rptdesign',TRUE,FALSE,FALSE,TRUE,NULL,'',NULL,FALSE,FALSE,FALSE,FALSE,45,FALSE);
INSERT INTO REPORT VALUES(60,'Customer List with Min Credit Limit','BIRT Report - Parameter Example','CustomerListWithMinCreditLimit.rptdesign',TRUE,FALSE,FALSE,TRUE,NULL,'',NULL,FALSE,FALSE,FALSE,FALSE,46,FALSE);
INSERT INTO REPORT VALUES(61,'Product Line Summary (BIRT)','BIRT Report - Chart Example','ProductInventorySummary.rptdesign',TRUE,FALSE,FALSE,TRUE,NULL,'',NULL,FALSE,FALSE,FALSE,FALSE,47,FALSE);
INSERT INTO REPORT_GROUP VALUES(3,'All Sample Reports','All Sample Reports');
INSERT INTO REPORT_GROUP VALUES(1,'ChartReports','Example ChartReports');
INSERT INTO REPORT_GROUP VALUES(2,'QueryReports','Example QueryReports');
INSERT INTO REPORT_GROUP VALUES(5,'JasperReports','Example JasperReports');
INSERT INTO REPORT_GROUP VALUES(6,'SpreadsheetReports','Example JXLS Spreadsheet Reports ');
INSERT INTO REPORT_GROUP VALUES(7,'BirtReports','Example BIRT Reports');

INSERT INTO REPORT_CHART VALUES(4,'Orders By Year and Month','XY Chart - Orders By Year and Month','select year_id, month_id,sum(quantityordered)\r\n from orderfact, time\r\nwhere orderfact.time_id = time.time_id\r\nand orderfact.orderdate > ''2002-12-31''\r\nand orderfact.orderdate < ''2005-01-01''\r\ngroup by year_id, month_id',2,600,400,'Month','Quantity Ordered',NULL,TRUE,TRUE,2,NULL,FALSE);
INSERT INTO REPORT_CHART VALUES(5,'Orders By Date','Time Chart - Orders By Date','select ''Orders'', sum(QUANTITYORDERED),orderdate \r\n from orderfact\r\nwhere orderfact.orderdate > ''2003-11-03'' \r\nand orderfact.orderdate < ''2003-11-11''\r\ngroup by orderdate\r\n\r\n',3,600,400,'Order Date','Order Quantity',NULL,FALSE,FALSE,2,NULL,FALSE);
INSERT INTO REPORT_CHART VALUES(9,'Orders By Product Line','Pie Chart - Orders By Product Line','select count(*), productline from orderdetails, orders, products where \r\norders.ordernumber = orderdetails.ordernumber\r\nand \r\norderdetails.productcode = products.productcode and orders.customernumber = $P{CustomerNumber}\r\ngroup by productline',1,600,400,'','',NULL,TRUE,TRUE,1,NULL,FALSE);
INSERT INTO REPORT_CHART VALUES(10,'Product Break Down By Line','Bar Chart - Product Break Down By Line','select count(*), '''', productline\r\nfrom products \r\ngroup by productline\r\norder by productline',0,600,400,'Product Name','Product Count',NULL,FALSE,FALSE,1,NULL,TRUE);
INSERT INTO REPORT_CHART VALUES(11,'Product Line Inventory','Ring Chart - Product Line Inventory','select sum(quantityinstock), productline \r\nfrom products \r\ngroup by productline\r\norder by productline',4,600,400,'','',NULL,FALSE,TRUE,1,NULL,TRUE);

INSERT INTO REPORT_USER VALUES(1,'admin','admin','1','admin@testdomain.com',0,42);
INSERT INTO REPORT_USER VALUES(5,'user','user','3','user@testdomain.com',0,NULL);

INSERT INTO USER_GROUP_MAP VALUES(1,3,0);
INSERT INTO USER_GROUP_MAP VALUES(1,7,1);
INSERT INTO USER_GROUP_MAP VALUES(1,1,2);
INSERT INTO USER_GROUP_MAP VALUES(1,5,3);
INSERT INTO USER_GROUP_MAP VALUES(1,2,4);
INSERT INTO USER_GROUP_MAP VALUES(1,6,5);
INSERT INTO USER_GROUP_MAP VALUES(5,1,0);
INSERT INTO USER_GROUP_MAP VALUES(5,5,1);
INSERT INTO USER_GROUP_MAP VALUES(5,2,2);
INSERT INTO REPORT_PARAMETER_MAP VALUES(38,9,TRUE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(38,20,TRUE,0,0,1);
INSERT INTO REPORT_PARAMETER_MAP VALUES(40,21,FALSE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(41,21,TRUE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(49,22,TRUE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(49,23,TRUE,0,1,1);
INSERT INTO REPORT_PARAMETER_MAP VALUES(49,19,FALSE,1,1,2);
INSERT INTO REPORT_PARAMETER_MAP VALUES(49,11,FALSE,2,1,3);
INSERT INTO REPORT_PARAMETER_MAP VALUES(50,24,TRUE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(53,25,FALSE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(53,22,TRUE,0,0,1);
INSERT INTO REPORT_PARAMETER_MAP VALUES(56,25,FALSE,0,0,0);
INSERT INTO REPORT_PARAMETER_MAP VALUES(56,9,TRUE,0,0,1);
INSERT INTO REPORT_PARAMETER_MAP VALUES(60,26,TRUE,0,0,0);

INSERT INTO REPORT_GROUP_MAP VALUES(1,14,0);
INSERT INTO REPORT_GROUP_MAP VALUES(1,41,1);
INSERT INTO REPORT_GROUP_MAP VALUES(1,13,2);
INSERT INTO REPORT_GROUP_MAP VALUES(1,46,3);
INSERT INTO REPORT_GROUP_MAP VALUES(1,47,4);
INSERT INTO REPORT_GROUP_MAP VALUES(1,42,5);
INSERT INTO REPORT_GROUP_MAP VALUES(2,39,0);
INSERT INTO REPORT_GROUP_MAP VALUES(2,37,1);
INSERT INTO REPORT_GROUP_MAP VALUES(2,40,2);
INSERT INTO REPORT_GROUP_MAP VALUES(2,38,3);
INSERT INTO REPORT_GROUP_MAP VALUES(2,33,4);
INSERT INTO REPORT_GROUP_MAP VALUES(5,50,0);
INSERT INTO REPORT_GROUP_MAP VALUES(5,48,1);
INSERT INTO REPORT_GROUP_MAP VALUES(5,56,2);
INSERT INTO REPORT_GROUP_MAP VALUES(5,49,3);
INSERT INTO REPORT_GROUP_MAP VALUES(5,57,4);
INSERT INTO REPORT_GROUP_MAP VALUES(6,53,0);
INSERT INTO REPORT_GROUP_MAP VALUES(6,54,1);
INSERT INTO REPORT_GROUP_MAP VALUES(6,55,2);
INSERT INTO REPORT_GROUP_MAP VALUES(7,61,0);
INSERT INTO REPORT_GROUP_MAP VALUES(7,60,1);
INSERT INTO REPORT_GROUP_MAP VALUES(7,59,2);
INSERT INTO REPORT_GROUP_MAP VALUES(7,58,3);
INSERT INTO REPORT_GROUP_MAP VALUES(3,61,0);
INSERT INTO REPORT_GROUP_MAP VALUES(3,60,1);
INSERT INTO REPORT_GROUP_MAP VALUES(3,59,2);
INSERT INTO REPORT_GROUP_MAP VALUES(3,58,3);
INSERT INTO REPORT_GROUP_MAP VALUES(3,56,4);
INSERT INTO REPORT_GROUP_MAP VALUES(3,50,5);
INSERT INTO REPORT_GROUP_MAP VALUES(3,39,6);
INSERT INTO REPORT_GROUP_MAP VALUES(3,57,7);
INSERT INTO REPORT_GROUP_MAP VALUES(3,48,8);
INSERT INTO REPORT_GROUP_MAP VALUES(3,53,9);
INSERT INTO REPORT_GROUP_MAP VALUES(3,37,10);
INSERT INTO REPORT_GROUP_MAP VALUES(3,55,11);
INSERT INTO REPORT_GROUP_MAP VALUES(3,40,12);
INSERT INTO REPORT_GROUP_MAP VALUES(3,14,13);
INSERT INTO REPORT_GROUP_MAP VALUES(3,41,14);
INSERT INTO REPORT_GROUP_MAP VALUES(3,13,15);
INSERT INTO REPORT_GROUP_MAP VALUES(3,38,16);
INSERT INTO REPORT_GROUP_MAP VALUES(3,46,17);
INSERT INTO REPORT_GROUP_MAP VALUES(3,47,18);
INSERT INTO REPORT_GROUP_MAP VALUES(3,54,19);
INSERT INTO REPORT_GROUP_MAP VALUES(3,49,20);
INSERT INTO REPORT_GROUP_MAP VALUES(3,42,21);
INSERT INTO REPORT_GROUP_MAP VALUES(3,33,22);

INSERT INTO OR_PROPERTIES VALUES(11,'base.directory','/home/jxb/applications/jakarta-tomcat-5.0.28/webapps/openreports/reports/');
INSERT INTO OR_PROPERTIES VALUES(1,'date.format','MM/dd/yyyy');
INSERT INTO OR_PROPERTIES VALUES(2,'mail.auth.password','');
INSERT INTO OR_PROPERTIES VALUES(3,'mail.auth.user','');
INSERT INTO OR_PROPERTIES VALUES(4,'mail.smtp.auth','false');
INSERT INTO OR_PROPERTIES VALUES(5,'mail.smtp.host','localhost');
INSERT INTO OR_PROPERTIES VALUES(6,'role.admin','admin');
INSERT INTO OR_PROPERTIES VALUES(7,'role.user','user');
INSERT INTO OR_PROPERTIES VALUES(8,'temp.directory','/home/jxb/applications/jakarta-tomcat-5.0.28/webapps/openreports/reports/temp/');
INSERT INTO OR_PROPERTIES VALUES(9,'queryreport.maxrows','1000');
INSERT INTO OR_PROPERTIES VALUES(10,'report.generation.directory','/home/jxb/applications/jakarta-tomcat-5.0.28/webapps/openreports/reports/generated/');
INSERT INTO REPORT_ALERT VALUES(2,'Budget Variance Alert','Budget Variance Alert','select sum(variance) from quadrant_actuals',2);
INSERT INTO REPORT_ALERT VALUES(3,'Motorcycle Inventory Alert','Motorcycle Inventory Alert','select sum(quantityinstock)\r\nfrom products \r\nwhere productline = ''Motorcycles''',2);

INSERT INTO REPORT_EXPORT_OPTIONS VALUES(16,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(17,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(19,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(23,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(24,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(25,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(26,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(27,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(28,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(32,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(33,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(34,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(35,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(36,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(39,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(40,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(41,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(42,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(43,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(44,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(45,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(46,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO REPORT_EXPORT_OPTIONS VALUES(47,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE);


INSERT INTO USER_SECURITY VALUES(5,'LOG_VIEWER_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'CHART_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'REPORT_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'GROUP_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'LOG_VIEWER_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'PARAMETER_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'DATASOURCE_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'SCHEDULER_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'UPLOAD_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'ROOT_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(5,'SCHEDULER_ROLE');
INSERT INTO USER_SECURITY VALUES(5,'REPORT_ADMIN_ROLE');
INSERT INTO USER_SECURITY VALUES(5,'UPLOAD_ROLE');
INSERT INTO USER_SECURITY VALUES(1,'ADVANCED_SCHEDULER_ROLE');
