alter table Blog drop constraint FK1FA3C24F2DD20D;
alter table Foo drop constraint FK114A61A27D6B;
alter table FooInfo drop constraint FK3A9D2A741A29ED1;
alter table MetricValue drop constraint FKFB5361811D79FA59;
alter table PromotionRuleParams drop constraint FK8854C0852C537632;
alter table TCustomerGroup drop constraint FKCB4D194D508DE1D;
alter table TCustomerGroup drop constraint FKCB4D194D45469C26;
alter table TDispatchingGift drop constraint FK2281D784E93B81C5;
alter table TDispatchingGift drop constraint FK2281D784DBBD74A1;
alter table TEvalMetrics drop constraint FKDEE6EB93DCB4061D;
alter table TEvalMetrics drop constraint FKDEE6EB93D1DE5F21;
alter table TPromotionPlan drop constraint FK77034A78508DE1D;
alter table TPromotionPlan drop constraint FK77034A784C1A050D;
alter table TPromotionPlan drop constraint FK77034A7858B8A0A0;
alter table TReportDefinition drop constraint FK86F6921B2C71B5CC;
alter table TReportParameters drop constraint FKDEC51EB2E57D617A;
alter table TReportParameters drop constraint FKDEC51EB2A08FA98A;
alter table TRolePermissions drop constraint FKAA8DB3AB1E777EC;
alter table TUserInfo drop constraint FK9A67B78DB73CCD56;
alter table TUserRoles drop constraint FKB30E97BEB1E777EC;
alter table TUserRoles drop constraint FKB30E97BEB73CCD56;
alter table authors drop constraint FKD977104835B728BB;
alter table authors drop constraint FKD9771048A302392F;

drop table Author;
drop table Bar;
drop table Blog;
drop table Book;
drop table Foo;
drop table FooInfo;
drop table MetricValue;
drop table PromotionRuleParams;
drop table TASource;
drop table TBSource;
drop table TCSource;
drop table TCustomerGroup;
drop table TDispatchingGift;
drop table TEvalMetrics;
drop table TEvaluation;
drop table TGift;
drop table TLog;
drop table TMetric;
drop table TPointType;
drop table TPromotionPlan;
drop table TReportDefinition;
drop table TReportParameter;
drop table TReportParameters;
drop table TReportTemplate;
drop table TRole;
drop table TRolePermissions;
drop table TRules;
drop table TUser;
drop table TUserInfo;
drop table TUserRoles;
drop table authors;

create table Author (id numeric(19,0) identity not null, name varchar(255) null, primary key (id));
create table Bar (id numeric(19,0) not null, name varchar(255) null, primary key (id));
create table Blog (id numeric(19,0) identity not null, name varchar(255) null, author numeric(19,0) null, primary key (id));
create table Book (id numeric(19,0) identity not null, name varchar(255) null, primary key (id));
create table Foo (id numeric(19,0) not null, amount numeric(19,2) null, date datetime null, name varchar(255) null, bar numeric(19,0) null, F varchar(255) null, I char(1) null, L varchar(255) null, primary key (id));
create table FooInfo (foo numeric(19,0) not null, val varchar(255) null, name varchar(80) not null, primary key (foo, name));
create table MetricValue (F_Id numeric(19,0) identity not null, F_DimensionType varchar(255) null, F_Dimension varchar(255) null, F_MetricId numeric(19,0) null, F_TargetType varchar(255) null, F_TargetId numeric(19,0) null, F_QuotaValue numeric(19,2) null, F_Frequence varchar(255) null, F_Date datetime null, primary key (F_Id));
create table PromotionRuleParams (PID numeric(19,0) not null, val varchar(255) null, name varchar(80) not null, primary key (PID, name));
create table TASource (id numeric(19,0) identity not null, name varchar(255) null, atype varchar(255) null, primary key (id));
create table TBSource (id numeric(19,0) identity not null, name varchar(255) null, btype varchar(255) null, primary key (id));
create table TCSource (id numeric(19,0) identity not null, name varchar(255) null, ctype varchar(255) null, primary key (id));
create table TCustomerGroup (idno numeric(19,0) identity not null, creationDate datetime null, name varchar(255) null, description varchar(255) null, rule varchar(255) null, creator varchar(255) null, evaluation numeric(19,0) null, parent numeric(19,0) null, primary key (idno));
create table TDispatchingGift (idno numeric(19,0) identity not null, applyDate datetime null, customer varchar(255) null, gift numeric(19,0) null, quantity int null, status int null, primary key (idno));
create table TEvalMetrics (eid numeric(19,0) not null, mid numeric(19,0) not null);
create table TEvaluation (idno numeric(19,0) identity not null, creationDate datetime null, creator varchar(255) null, description varchar(255) null, formula varchar(255) null, name varchar(255) null, type varchar(255) null, primary key (idno));
create table TGift (idno numeric(19,0) identity not null, availableQuantity int null, costPrice numeric(19,2) null, description varchar(255) null, exchangeRule varchar(255) null, marketPrice numeric(19,2) null, name varchar(255) null, seqno varchar(255) null unique, image image null, imageFileName varchar(255) null, primary key (idno));
create table TLog (id numeric(19,0) identity not null, log varchar(255) null, tablename varchar(255) null, sourceid numeric(19,0) null, primary key (id));
create table TMetric (idno numeric(19,0) identity not null, description varchar(255) null, formula varchar(255) null, type varchar(255) null, frequence varchar(255) null, name varchar(255) null, ratio varchar(255) null, unit varchar(255) null, primary key (idno));
create table TPointType (idno numeric(19,0) identity not null, description varchar(255) null, name varchar(255) null, primary key (idno));
create table TPromotionPlan (idno numeric(19,0) identity not null, creationDate datetime null, creator varchar(255) null, description varchar(255) null, endDate datetime null, evaluation numeric(19,0) null, name varchar(255) null, rule numeric(19,0) null, startDate datetime null, status varchar(255) null, target numeric(19,0) not null, primary key (idno));
create table TReportDefinition (idno numeric(19,0) identity not null, dataSource numeric(19,0) null, description varchar(255) null, name varchar(255) null, query varchar(255) null, type varchar(255) null, template numeric(19,0) null, primary key (idno));
create table TReportParameter (idno numeric(19,0) identity not null, value varchar(255) null, cname varchar(255) null, converter varchar(255) null, len int null, maxlen int null, maxvalue varchar(255) null, minlen int null, minvalue varchar(255) null, name varchar(255) null, req tinyint null, type varchar(255) null, action varchar(255) null, jspattern varchar(255) null, pattern varchar(255) null, patternmsg varchar(255) null, entityName varchar(255) null, operator varchar(255) null, is_key tinyint null, tagtype varchar(255) null, primary key (idno));
create table TReportParameters (reportId numeric(19,0) not null, paramId numeric(19,0) not null);
create table TReportTemplate (idno numeric(19,0) identity not null, content image null, description varchar(255) null, name varchar(255) null, primary key (idno));
create table TRole (idno numeric(19,0) identity not null, name varchar(255) null, description varchar(255) null, primary key (idno));
create table TRolePermissions (RoleId numeric(19,0) not null, Permission varchar(255) null);
create table TRules (idno numeric(19,0) identity not null, description varchar(255) null, name varchar(255) null, rule text null, type varchar(255) null, mapping text null, primary key (idno));
create table TUser (idno numeric(19,0) identity not null, creationDate datetime null, disabled tinyint null, disabledDate datetime null, ip varchar(255) null, lastAccessDate datetime null, name varchar(255) null, password varchar(255) null, superuser tinyint null, primary key (idno));
create table TUserInfo (userId numeric(19,0) not null, val varchar(255) null, name varchar(80) not null, primary key (userId, name));
create table TUserRoles (userId numeric(19,0) not null, roleId numeric(19,0) not null, primary key (userId, roleId));
create table authors (id numeric(19,0) not null, elt numeric(19,0) not null);
alter table Blog add constraint FK1FA3C24F2DD20D foreign key (author) references Author;
alter table Foo add constraint FK114A61A27D6B foreign key (bar) references Bar;
alter table FooInfo add constraint FK3A9D2A741A29ED1 foreign key (foo) references Foo;
alter table MetricValue add constraint FKFB5361811D79FA59 foreign key (F_MetricId) references TMetric;
alter table PromotionRuleParams add constraint FK8854C0852C537632 foreign key (PID) references TPromotionPlan;
alter table TCustomerGroup add constraint FKCB4D194D508DE1D foreign key (evaluation) references TEvaluation;
alter table TCustomerGroup add constraint FKCB4D194D45469C26 foreign key (parent) references TCustomerGroup;
alter table TDispatchingGift add constraint FK2281D784E93B81C5 foreign key (gift) references TGift;

alter table TEvalMetrics add constraint FKDEE6EB93DCB4061D foreign key (mid) references TMetric;
alter table TEvalMetrics add constraint FKDEE6EB93D1DE5F21 foreign key (eid) references TEvaluation;
alter table TPromotionPlan add constraint FK77034A78508DE1D foreign key (evaluation) references TEvaluation;
alter table TPromotionPlan add constraint FK77034A784C1A050D foreign key (target) references TCustomerGroup;
alter table TPromotionPlan add constraint FK77034A7858B8A0A0 foreign key (rule) references TRules;
alter table TReportDefinition add constraint FK86F6921B2C71B5CC foreign key (template) references TReportTemplate;
alter table TReportParameters add constraint FKDEC51EB2E57D617A foreign key (reportId) references TReportDefinition;
alter table TReportParameters add constraint FKDEC51EB2A08FA98A foreign key (paramId) references TReportParameter;
alter table TRolePermissions add constraint FKAA8DB3AB1E777EC foreign key (RoleId) references TRole;
alter table TUserInfo add constraint FK9A67B78DB73CCD56 foreign key (userId) references TUser;
alter table TUserRoles add constraint FKB30E97BEB1E777EC foreign key (roleId) references TRole;
alter table TUserRoles add constraint FKB30E97BEB73CCD56 foreign key (userId) references TUser;
alter table authors add constraint FKD977104835B728BB foreign key (id) references Book;
alter table authors add constraint FKD9771048A302392F foreign key (elt) references Author;

alter table REPORT drop constraint FK8FDF49343A53434B;
alter table REPORT drop constraint FK8FDF4934AD1AEEF4;
alter table REPORT drop constraint FK8FDF4934FBBB3EC9;
alter table REPORT_ALERT drop constraint FKF81C86713A53434B;
alter table REPORT_CHART drop constraint FKF836D4F33A53434B;
alter table REPORT_CHART drop constraint FKF836D4F3E08BB4B7;
alter table REPORT_GROUP_MAP drop constraint FKEF946211E08BB4B7;
alter table REPORT_GROUP_MAP drop constraint FKEF946211C487AF29;
alter table REPORT_LOG drop constraint FK901BE599CB12A22B;
alter table REPORT_LOG drop constraint FK901BE599E08BB4B7;
alter table REPORT_LOG drop constraint FK901BE59964AE609;
alter table REPORT_PARAMETER drop constraint FKBC64163E3A53434B;
alter table REPORT_PARAMETER_MAP drop constraint FK23FF1FBB5CC22769;
alter table REPORT_PARAMETER_MAP drop constraint FK23FF1FBBE08BB4B7;
alter table REPORT_USER drop constraint FK7364F3F6239E6839;
alter table USER_ALERT_MAP drop constraint FKD83C845CB12A22B;
alter table USER_ALERT_MAP drop constraint FKD83C845E08BB4B7;
alter table USER_ALERT_MAP drop constraint FKD83C84564AE609;
alter table USER_GROUP_MAP drop constraint FKC49EBE8CB12A22B;
alter table USER_GROUP_MAP drop constraint FKC49EBE8C487AF29;
alter table USER_SECURITY drop constraint FK7DE1C934CB12A22B;
drop table OR_PROPERTIES;
drop table REPORT;
drop table REPORT_ALERT;
drop table REPORT_CHART;
drop table REPORT_DATASOURCE;
drop table REPORT_EXPORT_OPTIONS;
drop table REPORT_GROUP;
drop table REPORT_GROUP_MAP;
drop table REPORT_LOG;
drop table REPORT_PARAMETER;
drop table REPORT_PARAMETER_MAP;
drop table REPORT_USER;
drop table TestUser;
drop table USER_ALERT_MAP;
drop table USER_GROUP_MAP;
drop table USER_SECURITY;
create table OR_PROPERTIES (PROPERTY_ID int identity not null, PROPERTY_KEY varchar(255) not null unique, PROPERTY_VALUE varchar(255) null, primary key (PROPERTY_ID));
create table REPORT (REPORT_ID int identity not null, NAME varchar(255) not null unique, DESCRIPTION varchar(255) not null, REPORT_FILE varchar(255) not null, PDF_EXPORT tinyint not null, CSV_EXPORT tinyint not null, XLS_EXPORT tinyint not null, HTML_EXPORT tinyint not null, RTF_EXPORT tinyint not null, TEXT_EXPORT tinyint not null, EXCEL_EXPORT tinyint not null, FILL_VIRTUAL tinyint not null, HIDDEN_REPORT tinyint not null, REPORT_QUERY text null, DATASOURCE_ID int null, CHART_ID int null, EXPORT_OPTION_ID int null, primary key (REPORT_ID));
create table REPORT_ALERT (ALERT_ID int identity not null, NAME varchar(255) not null unique, DESCRIPTION varchar(255) not null, ALERT_QUERY text not null, DATASOURCE_ID int null, primary key (ALERT_ID));
create table REPORT_CHART (CHART_ID int identity not null, NAME varchar(255) not null unique, DESCRIPTION varchar(255) not null, CHART_QUERY text not null, CHART_TYPE int not null, WIDTH int not null, HEIGHT int not null, X_AXIS_LABEL varchar(255) null, Y_AXIS_LABEL varchar(255) null, SHOW_LEGEND tinyint not null, SHOW_TITLE tinyint not null, SHOW_VALUES tinyint not null, PLOT_ORIENTATION int null, DATASOURCE_ID int null, REPORT_ID int null, primary key (CHART_ID));
create table REPORT_DATASOURCE (DATASOURCE_ID int identity not null, NAME varchar(255) not null unique, DRIVER varchar(255) null, URL varchar(255) not null, USERNAME varchar(255) null, PASSWORD varchar(255) null, MAX_IDLE int null, MAX_ACTIVE int null, MAX_WAIT numeric(19,0) null, VALIDATION_QUERY varchar(255) null, JNDI tinyint null, primary key (DATASOURCE_ID));
create table REPORT_EXPORT_OPTIONS (EXPORT_OPTION_ID int identity not null, XLS_REMOVE_EMPTY_SPACE tinyint not null, XLS_ONE_PAGE_PER_SHEET tinyint not null, XLS_AUTO_DETECT_CELL tinyint not null, XLS_WHITE_BACKGROUND tinyint not null, HTML_REMOVE_EMPTY_SPACE tinyint not null, HTML_WHITE_BACKGROUND tinyint not null, HTML_USE_IMAGES tinyint not null, HTML_WRAP_BREAK tinyint not null, primary key (EXPORT_OPTION_ID));
create table REPORT_GROUP (GROUP_ID int identity not null, NAME varchar(255) not null unique, DESCRIPTION varchar(255) not null, primary key (GROUP_ID));
create table REPORT_GROUP_MAP (GROUP_ID int not null, REPORT_ID int not null, MAP_ID int not null, primary key (GROUP_ID, MAP_ID));
create table REPORT_LOG (LOG_ID int identity not null, START_TIME datetime null, END_TIME datetime null, STATUS varchar(255) null, MESSAGE text null, REPORT_ID int null, USER_ID int null, ALERT_ID int null, primary key (LOG_ID));
create table REPORT_PARAMETER (PARAMETER_ID int identity not null, NAME varchar(255) not null unique, TYPE varchar(255) not null, CLASSNAME varchar(255) not null, DATA text null, DATASOURCE_ID int null, DESCRIPTION varchar(255) null, REQUIRED tinyint null, MULTI_SELECT tinyint null, primary key (PARAMETER_ID));
create table REPORT_PARAMETER_MAP (REPORT_ID int not null, PARAMETER_ID int null, REQUIRED tinyint null, SORT_ORDER int null, STEP int null, MAP_ID int not null, primary key (REPORT_ID, MAP_ID));
create table REPORT_USER (REPORTUSER_ID int identity not null, NAME varchar(255) not null unique, PASSWORD varchar(255) not null, EXTERNAL_ID varchar(255) null, EMAIL_ADDRESS varchar(255) null, PDF_EXPORT_TYPE int not null, DEFAULT_REPORT_ID int null, primary key (REPORTUSER_ID));
create table TestUser (idno numeric(19,0) identity not null, userid numeric(19,0) null, amount numeric(19,2) null, creationDate datetime null, description varchar(255) null, name varchar(255) null, password varchar(255) null, primary key (idno));
create table USER_ALERT_MAP (USER_ID int not null, ALERT_ID int null, REPORT_ID int null, ALERT_LIMIT int null, ALERT_OPERATOR varchar(255) null, MAP_ID int not null, primary key (USER_ID, MAP_ID));
create table USER_GROUP_MAP (USER_ID int not null, GROUP_ID int not null, MAP_ID int not null, primary key (USER_ID, MAP_ID));
create table USER_SECURITY (USER_ID int not null, ROLE_NAME varchar(255) null);
alter table REPORT add constraint FK8FDF49343A53434B foreign key (DATASOURCE_ID) references REPORT_DATASOURCE;
alter table REPORT add constraint FK8FDF4934AD1AEEF4 foreign key (EXPORT_OPTION_ID) references REPORT_EXPORT_OPTIONS;
alter table REPORT add constraint FK8FDF4934FBBB3EC9 foreign key (CHART_ID) references REPORT_CHART;
alter table REPORT_ALERT add constraint FKF81C86713A53434B foreign key (DATASOURCE_ID) references REPORT_DATASOURCE;
alter table REPORT_CHART add constraint FKF836D4F33A53434B foreign key (DATASOURCE_ID) references REPORT_DATASOURCE;
alter table REPORT_CHART add constraint FKF836D4F3E08BB4B7 foreign key (REPORT_ID) references REPORT;
alter table REPORT_GROUP_MAP add constraint FKEF946211E08BB4B7 foreign key (REPORT_ID) references REPORT;
alter table REPORT_GROUP_MAP add constraint FKEF946211C487AF29 foreign key (GROUP_ID) references REPORT_GROUP;
alter table REPORT_LOG add constraint FK901BE599CB12A22B foreign key (USER_ID) references REPORT_USER;
alter table REPORT_LOG add constraint FK901BE599E08BB4B7 foreign key (REPORT_ID) references REPORT;
alter table REPORT_LOG add constraint FK901BE59964AE609 foreign key (ALERT_ID) references REPORT_ALERT;
alter table REPORT_PARAMETER add constraint FKBC64163E3A53434B foreign key (DATASOURCE_ID) references REPORT_DATASOURCE;
alter table REPORT_PARAMETER_MAP add constraint FK23FF1FBB5CC22769 foreign key (PARAMETER_ID) references REPORT_PARAMETER;
alter table REPORT_PARAMETER_MAP add constraint FK23FF1FBBE08BB4B7 foreign key (REPORT_ID) references REPORT;
alter table REPORT_USER add constraint FK7364F3F6239E6839 foreign key (DEFAULT_REPORT_ID) references REPORT;
alter table USER_ALERT_MAP add constraint FKD83C845CB12A22B foreign key (USER_ID) references REPORT_USER;
alter table USER_ALERT_MAP add constraint FKD83C845E08BB4B7 foreign key (REPORT_ID) references REPORT;
alter table USER_ALERT_MAP add constraint FKD83C84564AE609 foreign key (ALERT_ID) references REPORT_ALERT;
alter table USER_GROUP_MAP add constraint FKC49EBE8CB12A22B foreign key (USER_ID) references REPORT_USER;
alter table USER_GROUP_MAP add constraint FKC49EBE8C487AF29 foreign key (GROUP_ID) references REPORT_GROUP;
alter table USER_SECURITY add constraint FK7DE1C934CB12A22B foreign key (USER_ID) references REPORT_USER;

