/* Generated By:JJTree: Do not edit this line. /Users/jeffrey/Documents/jxb/ninecube/saturn/src/net/ninecube/formula/parser/FormulaParserTreeConstants.java */

package net.ninecube.formula.parser;

public interface FormulaParserTreeConstants
{
  public int JJTFORMULA = 0;
  public int JJTVOID = 1;
  public int JJTARITH = 2;
  public int JJTFACTOR = 3;
  public int JJTFUNCTION = 4;
  public int JJTARGUMENT = 5;


  public String[] jjtNodeName = {
    "Formula",
    "void",
    "Arith",
    "Factor",
    "Function",
    "Argument",
  };
}
