/* Generated By:JJTree&JavaCC: Do not edit this line. FormulaParserConstants.java */
package net.ninecube.formula.parser;

public interface FormulaParserConstants {

  int EOF = 0;
  int DECIMAL_LITERAL = 4;
  int IDENTIFIER = 5;
  int UNICODE = 6;
  int LETTER = 7;
  int DIGIT = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<DECIMAL_LITERAL>",
    "<IDENTIFIER>",
    "<UNICODE>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"%\"",
    "\",\"",
    "\":\"",
  };

}
